### ISSUE TITLE
Slowness

### ISSUE THREAD

**Issue by honza** [wikimatze/hammer.vim#18]
I' not sure why but this plugin was causing some major slowness in my vim. It would take like 5 seconds before terminal vim would open a file. Removing the plugin made my vim blazing fast again. Thoughts?

Using latest hammer.vim and latest vim. Thanks

**Comment by ghost** [comment]
OK, that's no good, but I'm not sure why that's happening. 
It isn't something I've run into personally, and you're the first to report that problem.
Is it happening for other people, too?

**Comment by honza** [comment]
I'm happy to help you debug it.

**Comment by honza** [comment]
I did some further analysis. I turns out that it wasn't your plugin that was causing it. I'm not exactly sure what's causing it. My Mac is acting really weird. Once I restarted it, vim was super slow again. I apologize for raising a false alarm and for wasting your time!

**Comment by ghost** [comment]
Don't worry about it. :-)

**Comment by thedjinn** [comment]
The current version of hammer is still slow. I did a `--startuptime` analysis showing that hammer takes more than a second to initialize. You can find my profile data here: https://gist.github.com/1684417

**Comment by ghost** [comment]
@thedjinn I think #38 addresses the issue of slow startup time… Let me know if that isn't the case for you.
