### ISSUE TITLE
Problem with pathogen

### ISSUE THREAD

**Issue by maba** [wikimatze/hammer.vim#2]
Hi, 
with this new version we have a problem with PATH when we use pathogen to load plugins.

```
$LOAD_PATH.unshift(File.join(ENV['HOME'], '.vim', 'plugin',
                   'vim-markdown-preview'))

require('kramdown/kramdown')
```

Path is fixed but I have not `.vim/plugin/`folder because I have installed VMP under `autoload/bundle/markdown-preview` (e.g.).

```
Error detected while processing function PreviewMKD:
line   91:
LoadError: (eval):7:in `require': no such file to load -- kramdown/kramdown
E488: Trailing characters
```

And.. great work :)

**Comment by ghost** [comment]
Hi  
Will adding $HOME/.vim/autoload/bundle/markdown-preview/ fix this issue for you?  
If you can, please try it out by replacing the $LOAD_PATH line appropriately.  
If you like, you can do so in your own fork & I will merge it.  

Thanks for the report and your contributions!  
Rob

**Comment by maba** [comment]
The correct path is (no autoload/bundle, my mistake):
    .vim/bundle/markdown-preview/plugin/vim-markdown-preview
so
    $LOAD_PATH.unshift(File.join(ENV['HOME'], '.vim', 'bundle', 'markdown-preview', 'plugin', 'vim-markdown-preview'))
and yes in this way it works but `markdown-preview` main folder name is my personal choice for this plugin, anyone can rename this folder as he wants.

I don't know if pathogen create a env var lile "THIS_PLUGIN_PATH" to use in these cases.

I haven't edited yet my fork because I'm not familiar with Ruby.

**Comment by ghost** [comment]
Hi,  
I am not familiar with "pathogen". From what I understand, it will look inside $HOME/.vim/bundle - please correct me if I'm wrong ;-) I will install it here, and see what I can do. I will update this ticket when I am done.

**Comment by maba** [comment]
Yep, you're right.

I think that I fixed it.
Now update my fork, please try it in your installation.

**Comment by maba** [comment]
Mmm.. it works for a while but now I've some problems.

**Comment by ghost** [comment]
We're on the same page :-) Unfortunately, __FILE__ will evaluate to something like "(eval)" when executed in the context of vim, and if i remember correctly :-) Lemme know if you have any luck, I will keep trying other solutions too.

**Comment by maba** [comment]
Probably you are right.
With
    require File.expand_path(File.dirname(**FILE**)) + '/vim-markdown-preview/kramdown/kramdown'
and no LOAD_PATH it works but it doesn't find `document`. This is right.
If I enable my LOAD_PATH it fully works.. why?? O.o

Other little problem, buy maybe it can be due to my dirty test.. 
    :! open /tmp/README.mkd.html
    E488: Trailing characters

**Comment by maba** [comment]
Ok.. try it:

```
kramdown_libdir = File.expand_path(File.dirname(__FILE__)) + '/vim-markdown-preview'
$LOAD_PATH.unshift(kramdown_libdir)

require('kramdown/kramdown')
```

**Comment by ghost** [comment]
Hi,  
I will need to check this out later today. I _think_ it could be broken but I hope not :-) I think a better solution would be to add $VIMRUNTIME to $LOAD_PATH. Thanks a lot for your contributions and time, I appreciate it. 

Rob

**Comment by ghost** [comment]
Hi,  
This issue should be fixed  
(see [this commit](http://github.com/robgleeson/vim-markdown-preview/commit/9a0587f2e0511420289e7c026d563caac2021dce))

As long as vmp's directory structure is respected(plugin/ exists, with vim-markdown-preview inside) I see no reason why this will not work. 

Can you please confirm?  
Thanks,  
Rob

**Comment by maba** [comment]
Yep! Now it works fine! :)

Remain only the: 
    :! open /tmp/README.mkd.html
    E488: Trailing characters

Can you see it?

**Comment by ghost** [comment]
Okay, awesome :-)  
I think I've fixed the other error you reported (see [this commit](http://github.com/robgleeson/vim-markdown-preview/commit/f411f2ee2443a10d923ba93fd88b3abec577fd29))

Does that work for you? No trailing characters error, and it won't wait for user input to continue.

**Comment by maba** [comment]
Yes, now it fully works!
Thanks Rob!

**Comment by ghost** [comment]
No problem Marco :-)
