### ISSUE TITLE
Vim: Caught deadly signal SEGV Vim: Finished. when use with rvm on ruby version greater than 1.8.7

### ISSUE THREAD

**Issue by wikimatze** [wikimatze/hammer.vim#22]
I installed only this plugin with the pathogen script and installed different version of ruby (1.8.7, 1.9.1, 1.9.2). When I switch to 1.8.7 the plugin is working and vim starts normally. When I switched to 1.9.1 with rvm use 1.9.1 vim doesn't start anymore and I get the error message Vim: Caught deadly signal SEGV Vim: Finished.

**Comment by ghost** [comment]
Add this to your `$HOME/.zshrc` (replace mvim with vim, gvim, or whatever you prefer):

``` bash
mvim()
{
  (unset GEM_PATH GEM_HOME; command mvim "$@")
}
```

This occurs because RVM clobbers the shell environment, and causes the loading of C extensions built against a different ruby than what Vim is linked against.

**Comment by wikimatze** [comment]
That was the solution, thanks rob for this awesome plugin.

**Comment by paractmol** [comment]
Yeah! Thank you!
