### ISSUE TITLE
inline POD in .{pl,pm} files

### ISSUE THREAD

**Issue by trapd00r** [wikimatze/hammer.vim#24]
Would it be hard to add support for inline POD in .pm (perl module) and perhaps also .pl (perl file)?
What I think might be an obstacle is the fact that _some_ people document their methods with POD where they declare them; that is, you can't count on finding _only_ POD after a 

```
=pod
```

declaration.

But POD is very well specified, and perhaps there's some magical ruby modules for dealing with it nicely? It'd be _very_ useful for me.

**Comment by ghost** [comment]
I'm not too familiar with POD. I'd prefer to use something from Perl to do the parsing. 
Do you know of anything? 
Can `POD::Simple::HTML` extract POD documentation from Perl modules?

**Comment by trapd00r** [comment]
Absolutely: 

```
#!/usr/bin/perl
use strict;
use warnings FATAL => 'all';

use Pod::Simple::HTML;

my $p = Pod::Simple::HTML->new;

my $html;
$p->output_string( \$html );
$p->parse_from_file( shift // glob("*.pm") || 'lib/*.pm');
```

**Comment by ghost** [comment]
I haven't forgotten about this issue, I'm trying to juggle time to be able to spend some time on implementing it, though.

**Comment by trapd00r** [comment]
No worries!

If you tell me where the code should go, and how we 'use perl' in viml, I could give it a shot. After all, I speak Perl fluently. :)

**Comment by ghost** [comment]
@trapd00r

To support this feature properly(and others, in the future) I'd like to rewrite the internals of Hammer. 
It would be a lot easier to have `bootstrap`, which could be sourced by `hammer.vim`, that'd load any Ruby-related classes and modules, then ideally, the Hammer() function would be one call to a Ruby method.

At the moment it is hard to extend(and, even read through) because of the mix of Ruby and VimL code.
I'd like to do that before I implement this feature, but I began work on that rewrite over the weekend.

**Comment by trapd00r** [comment]
Excellent! Looking forward to it. It'd be nice if it was aware that it can be extended with 'plugins'. That is, if I want to add support for $filetype, I'd just hack it up and drop it in the appropriate place and it'd work automagically. 
I think that making it easier for users to contribute would allow for you to concentrate on more important stuff, like coffee breaks. :-) 

I just want you to know that this is by _far_ the most useful vim plugin I've seen. It's so simple (the idea, at least!) and it does what it claims to, nothing more. Love it!

Cheers!

**Comment by ghost** [comment]
Thanks, great to hear! :-)

Yeah, the "plugin" approach would be a cool idea, github-markup handles mapping a file extension to a renderer, but there's no reason we couldn't add a `renderer/` directory that would be auto loaded so people could map custom file extensions to their own renderers, or extend the defaults we've got in place already.

**Comment by ghost** [comment]
@trapd00r 

The feature you'd like to add should be really easy to implement since this commit:
https://github.com/robgleeson/hammer.vim/commit/a35cc43de3ac7188efe2ab78fb2ba418c40d6322

I've added support for custom renderers, and there is an example renderer in `plugin/hammer.vim/renderers` (for HTML).
Would you like to write one for Perl (using Perl, of course :)) that can parse `.pod` & `.pl` files. I'll add it to the repository whenever you can (posting the code to this issue would work as well, if thats easier).

**Comment by ghost** [comment]
Sorry, I forgot to say, the Perl script should accept input from $stdin, and write its output to $stdout.

**Comment by trapd00r** [comment]
Hi Rob, 

I didn't quite get what the html renderer actually do, but something like this for pod, perhaps:

```
command Hammer::ENV.browser, /pl|pm|pod/
```

Here's a POD parser that takes input from stdin and prints html on stdout:

```
#!/usr/bin/perl
use strict;
use warnings FATAL => 'all';
use Pod::Simple::HTML;

my $parser = Pod::Simple::HTML->new;

$parser->output_string(\my $html);

my $fh = *STDIN;
$parser->parse_file( $fh );

print $html;
```

Can test it with something like

```
curl -s htps:/raw.github.com/trapd0r/Term-ExtendedColor/master/lib/Term/ExtendedColor.pm | perl parse.pl > foo.html && firefox foo.html
```

Does this look ok?

**Comment by ghost** [comment]
Yeah, looks great! I have to go shopping right now, but when I get back I'll add it as a command.

**Comment by ghost** [comment]
Is there a Perl module or file you could recommend I test with?

**Comment by ghost** [comment]
Alright, this feature should be working now, I tested with a Perl module from the `ack` project.

**Comment by trapd00r** [comment]
Great, sorry for the late reply but I'm trying (again! :)) to compile vim with ruby support. That's fixed now, however:

```
> ./src/vi -c :q
github-markup is missing: Please run `gem install github-markup`. Set g:HammerQuiet to 1 to silence this message
Press ENTER or type command to continue
scp1@shiva:pts/2-> /home » scp1 » dev » vim () 
> su
Password: 
[root@shiva vim]# gem install github-markup
Successfully installed github-markup-0.7.0
1 gem installed
Installing ri documentation for github-markup-0.7.0...
Installing RDoc documentation for github-markup-0.7.0...
[root@shiva vim]# exit
scp1@shiva:pts/2-> /home » scp1 » dev » vim () 
> ./src/vi -c :q
github-markup is missing: Please run `gem install github-markup`. Set g:HammerQuiet to 1 to silence this message
Press ENTER or type command to continue

> \ls -Al /usr/lib/ruby/gems/1.9.1/gems/
drwx------ 5 root root 4096 Dec 13 15:29 github-markup-0.7.0
drwxr-xr-x 3 root root 4096 Nov 19 07:59 rake-0.9.2.2
drwxr-xr-x 3 root root 4096 Nov 19 07:59 rdoc-3.9.4
drwx------ 6 root root 4096 Dec 13 13:40 redcarpet-2.0.0
```

**Comment by ghost** [comment]
Do `ruby -v` at your shell and inside vim match up? That is usually the cause of those errors.

**Comment by trapd00r** [comment]
Yeah, it automagically solved itself when I forced an upgrade of ruby.
However... 

```
:Hammer
Error detected while processing function Hammer:
line    2:
NameError: undefined local variable or method `buffer' for main:Object
```

Which I assume is **plugin/hammer.vim/bootstap.vim:40**

**Comment by ghost** [comment]
Hm, interesting, it must be a difference between our Vim versions (I guess). I'll fix that now.

**Comment by ghost** [comment]
Can you pull, and try again?

**Comment by trapd00r** [comment]
My version:

VIM - Vi IMproved 7.3 (2010 Aug 15, compiled Dec 13 2011 13:40:13)
Included patches: 1-353

**Comment by trapd00r** [comment]
Pulled,

```
Error detected while processing function Hammer:
line    4:
NoMethodError: undefined method `flush' for #<Object:0x848053c>
```

**Comment by ghost** [comment]
Oh uh, we've had this error before - on a separate issue, it has something to do with Ruby 1.9, and Vim. 
Let me see if we ever solved that.

**Comment by trapd00r** [comment]
Oh crap.

:Hammering markdown files does work, I only get this error with pod.

**Comment by ghost** [comment]
Okay, we never really figured out a solution (only a probable cause - calling some methods on Kernel, a core Ruby module, while using Ruby 1.9 and Vim).

You can see the issue here: 
https://github.com/robgleeson/hammer.vim/issues/19

**Comment by ghost** [comment]
Yeah, I know that github-markup uses popen3 to talk to your perl script, and that is the exact same problem we had on #19, I was calling popen3 as well, and getting that error on Ruby 1.9.

The solution was to get rid of the call to popen3 and communicate through files(writing content, then reading it from there) but that won't work for this.

**Comment by ghost** [comment]
So, it may have nothing to do with the Kernel module after all, but the person who wrote the fix or patch hinted at Kernel, 'open3' is a separate standard library in Ruby, though.

**Comment by trapd00r** [comment]
I see. Perhaps this means that I'll get another chance to build vim, this time against 1.8 :D

**Comment by trapd00r** [comment]
Yeah, I can reproduce  :ruby `date`   etc, it dies with the same error message.

**Comment by ghost** [comment]
Yeah, I'd say try 1.8, if you have the time :)

**Comment by ghost** [comment]
How did this work out for you? 
No worries if you haven't had the time or don't have the effort to build with Ruby 1.8.
I'd like to merge this branch with master, soon, though so it'd be nice to have a second person confirm it as working :)

**Comment by trapd00r** [comment]
I've been having some trouble building 1.8 again... perhaps there's some tool like perlbrew that makes building and using various versions of ruby much easier?

I'll try again tomorrow - now there's christmas and I'm supposed to do other things than 'sitting in front of the computer all day' ... :-)

**Comment by ghost** [comment]
Yeah, I'd recommend [rbenv](https://github.com/sstephenson/rbenv) and [ruby-build](https://github.com/sstephenson/ruby-build).
When you've got both installed, you can do:
`$ rbenv install 1.8.7-pXXX`

But hey, no worries, enjoy Xmas! :-)
