### ISSUE TITLE
Does not work in new unsaved buffer

### ISSUE THREAD

**Issue by smith** [wikimatze/hammer.vim#3]
Running :Mm in a window on a new buffer ([No Name]) that has not yet been saved to a file gives me this:

```
Error detected while processing function PreviewMKD:
line   93:
TypeError: (eval):68:in `basename': can't convert nil into String
```

**Comment by ghost** [comment]
Closed by 5a595af3a500a1a5f6feb82580c00206071f0dae  
Fix included in the 1.0.1 release
