### ISSUE TITLE
MacVim 7.3 + Janus + Hammer does not open

### ISSUE THREAD

**Issue by bijzz** [wikimatze/hammer.vim#30]
Hi, i am using MacVim 7.3. I got the *.app from the official website. I also use Janus for vim and recently added hammer as an vim_plugin_task in my .janus.rake file. Launching the MacVim application does not show the MacVim window anymore. I can see the MacVim menubar + its dock icon though. 

When i enter mvim in the command line i get the msg ( github-markup is missing: Please run `gem install github-markup`. Set g:HammerQuiet to 1 to silence this message ) but nothing else.
Editing my bash .profile 

`````` mvim()
{  (unset GEM_PATH GEM_HOME; command mvim "$@")  } ```
like it is recommended in some other Issues does not lead to different results.

Heres my "ruby --version":
```ruby 1.9.2p290 (2011-07-09 revision 32553) [x86_64-darwin11.1.0]```

my "gem env":
```RubyGems Environment:
  - RUBYGEMS VERSION: 1.3.7
  - RUBY VERSION: 1.9.2 (2011-07-09 patchlevel 290) [x86_64-darwin11.1.0]
  - INSTALLATION DIRECTORY: /usr/local/Cellar/ruby/1.9.2-p290/lib/ruby/gems/1.9.1
  - RUBY EXECUTABLE: /usr/local/Cellar/ruby/1.9.2-p290/bin/ruby
  - EXECUTABLE DIRECTORY: /usr/local/Cellar/ruby/1.9.2-p290/bin
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86_64-darwin-11
  - GEM PATHS:
     - /usr/local/Cellar/ruby/1.9.2-p290/lib/ruby/gems/1.9.1
     - /Users/user/.gem/ruby/1.9.1
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :benchmark => false
     - :backtrace => false
     - :bulk_threshold => 1000
  - REMOTE SOURCES:
     - http://rubygems.org/
``````

and my "gem list":
`cheat (1.3.0)
github-markup (0.5.3)
minitest (2.6.0, 1.6.0)
rake (0.9.2, 0.8.7)
rdoc (3.9.4, 2.5.8)
redcarpet (1.17.2)`

**Comment by ghost** [comment]
What is the output of `:ruby p RUBY_DESCRIPTION` from inside vim?

**Comment by bijzz** [comment]
Hi, now im a little bit confused about my setup.

So i figure i have vim 7.3 installed. Vim --version tells me among others "Compiled by root@apple.com". So i suppose its prebuilt and shipped with OSX. I also find "-ruby" in the --version output. Therefore your command tells me that the command is not available in this version. 

Yet i have mvim 7.3 from their website. MVim --version also says +ruby. Therefore that version should work with hammer, right? Maybe mvim is set up for some default ruby version and i messed it up by installing the newest ruby version at some time (using homebrew). Unfortunately i cannot enter the :ruby p RUBY_DESCRIPTION in mvim as it does not start up. 

So... could it be that i have to either compile mvim with my ruby version or tell mvim somehow to use the system default ruby version? Thanks for any hints in the right direction.

**Comment by ghost** [comment]
Run: 

``` shell
$ mvim -v
```

Then run this in Vim: 
`:ruby p RUBY_DESCRIPTION`

**Comment by bijzz** [comment]
mvim immediately jumps back to command line, like that:

`~ $ mvim -v
~ $ github-markup is missing: Please run `gem install github-markup`. Set g:HammerQuiet to 1 to silence this messageAbort trap: 6
~ $`

Im not able to enter anything :/.
Starting just `vim` and `:ruby p RUBY_DESCRIPTION` gives me the `E319: Sorry this command is not available in this version`

**Comment by ghost** [comment]
Alright, add `let g:HammerQuiet = 1` to your $HOME/.vimrc

**Comment by bijzz** [comment]
ah,

now it starts up and indeed it says `"ruby 1.8.7 (2010-01-10 patchlevel 249) [universal-darwin11.0]"` which is unequal to my 1.9.2 ruby/gem installation. Whats the best way to get things running with hammer? Can i tell mvim to use ruby system default, but then the gems are only installed for 1.9.2 !? Or rather try to brew mvim?

**Comment by ghost** [comment]
You can't, unless you rebuild macvim to be linked against Ruby 1.9.
If you install the gems(github-markup, redcarpet) on your system Ruby, Hammer will work.

**Comment by bijzz** [comment]
awesome it works.

For anybody with the same issue: No need to change the symlinks of your Homebrew setup. Just enter your system ruby installation directory ( /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/bin/ruby for me on OSX Lion) and install the necessary gems ( ./gem install ..).

Btw. a remark: When a fool like me trys to render an unsaved file it just says `It is not possible to render  files. Missing dependency?` An output mentioning to save the file first would be more foolproof.

Anyway, thanks for your help.

**Comment by ghost** [comment]
Glad to hear it is working for you.
If the second part of your reply is something you want to see fixed, please open a separate issue. Thanks!
