### ISSUE TITLE
require 'rubygems'

### ISSUE THREAD

**Issue by trapd00r** [wikimatze/hammer.vim#31]
Hi Rob,

Fresh install of Vim and hammer.vim welcomes me with the following message:

```
Error detected while processing /home/scp1/etc/vim/bundle/hammer.vim/plugin/hammer.vim/hammer.vim:
line    5:
LoadError: (eval):0:in `require': no such file to load -- rubygems
```

I assume that rubygems is a package/module, but how do I install it? 

```
ERROR:  Could not find a valid gem 'rubygems' (>= 0) in any repository
```

**Comment by ghost** [comment]
Hey Magnus

Can you run the following in vim: `:ruby p RUBY_DESCRIPTION` and paste the output here?
Do you have one installation of Ruby present or many?  Ruby 1.9 is shipped with rubygems but older versions aren't so you might have to install it through your package manager.

**Comment by trapd00r** [comment]
```
"ruby 1.8.7 (2011-02-18 patchlevel 334) [i686-linux]"
```

I built against the wrong ruby (have 1.8.7 and 1.9), problem solved. :-)

**Comment by ghost** [comment]
Ah, happy to hear all is good again!
