### ISSUE TITLE
Redcloth RbConfig deprecated

### ISSUE THREAD

**Issue by trapd00r** [wikimatze/hammer.vim#32]
Hi Rob,

Vim build against Ruby 1.9.1 with the latest Hammer and RedCloth 4.2.8 - whenever I start Vim I get this error message:

```
/usr/lib/ruby/gems/1.9.1/gems/RedCloth-4.2.8/lib/redcloth.rb:10: Use RbConfig instead of obsolete and deprecated Config.
```

:Hammer'ing markdown and pod works, but the message is still annoying.

**Comment by ghost** [comment]
Hey,

Are you sure you need/want RedCloth? 
It is for Textile. 'redcarpet' is the guy for markdown.

**Comment by trapd00r** [comment]
Yeah, I know - sometimes I have to deal with textile though so I figured if there were some obvious simple fix :)

**Comment by ghost** [comment]
Ahh, yeah it is a simple fix but it'd need to happen inside RedCloth.
I sent a pull request for them: https://github.com/jgarber/redcloth/pull/12/

**Comment by ghost** [comment]
There is also: https://github.com/jgarber/redcloth/pull/11
I closed my own pull request. It is up to the RedCarpet maintainer to fix that now, though.

**Comment by trapd00r** [comment]
Thank you! Will patch it myself in the meantime.
