### ISSUE TITLE
Allow alternate file extensions for markdown

### ISSUE THREAD

**Issue by tylerball** [wikimatze/hammer.vim#33]
The [ikiwki](http://ikiwiki.info/features/#index3h2) wiki software requires that markdown files have the ".mdwn" extension. GitHub also allows the ".md" extension. It would be great to be able to :Hammer these files.

**Comment by ghost** [comment]
I'm re-writing hammer on another branch, but i'll add this feature when I merge into master.

**Comment by tylerball** [comment]
Awesome, thanks!

**Comment by ghost** [comment]
The dependency list has changed(got bigger :() so you might need to install one or two dependencies before Hammer can boot. The README covers it, though.
