### ISSUE TITLE
Hammer dependencies missing tilt, albino

### ISSUE THREAD

**Issue by wikimatze** [wikimatze/hammer.vim#34]
Hi Rob,

I installed a new version of your great plugin and now when I run :Hammer in my MacVim 7.3 installation I'm getting the error message mentioned in title. In the documentation I can't find any hint which additional gems or other stuff I need? I installed the gems and still got the error messages.

Thanks for this very good plugin.

Matthias

**Comment by ghost** [comment]
I hope to have time for a fix sometime soon (during the week).
The master branch is a mess at the moment, I never got time to 
finish the rewrite properly and merged too early.

I think this is a easy fix, though.

**Comment by wikimatze** [comment]
Hi Robert, no problem I can wait for the next release of this great plugin - take your time to develop your Ed DSL.

**Comment by OJ** [comment]
Also, the documentation doesn't say to install the 'albino' or 'redcarpet' gems, but I needed both of those (MacOSX Lion) to make it run.

Cheers!

**Comment by wikimatze** [comment]
@OJ That's true.
@robgleeson should we help you with the documentation and the coding to maintain this great plugin?

**Comment by ghost** [comment]
@matthias-guenther Yes, certainly. I do not have the time to maintain this plugin properly anymore.
Would you like to be a contributor?

**Comment by wikimatze** [comment]
@robgleeson yeah, it would be nice if you can add me on the contributor list - I hope I can support this plugin as much as I can. And this will be then my first experience as a contributor on an github project. Just le me know if this is okay.

**Comment by ghost** [comment]
Added, & no problem!

**Comment by wikimatze** [comment]
Problem is solved, had a native installation of ruby and this overwrote the rubygems settings of my rbenv installation.

**Comment by henry4j** [comment]
I have the same issue. How did you solve this problem?

**Comment by wikimatze** [comment]
@henry4j are you using MacVim?

**Comment by henry4j** [comment]
Yes, I am using MacVim. I use things as follows:

$ rvm install 1.8.7-head
$ ruby -v
ruby 1.8.7 (2012-02-08 patchlevel 358) [i686-darwin11.3.0]

$ alias vim='/Applications/MacVim.app/Contents/MacOS/Vim'

**Comment by wikimatze** [comment]
I see, I'm using rben (https://github.com/sstephenson/rbenv) and got problems with the missing dependencies. I investigated which ruby bindings MacVim uses and found that it takes a different path than the rbenv settings. I deleted /System/Library/Framework/Ruby on my Mac and create a symlink to my actual rbenv ruby setting with `ln -s $HOME/.rbenv/libexec/rbenv /usr/local/ruby`.

This worked fine and now the missing gems could be loaded. I tried the whole process under Unix with ubuntu and this sadly didn't work.

Yesterday evening I tried to require other gems in a vim plugin and discovered that the correct detection of your ruby libs is the main problem in vim. This issue must be common to other plugin using the same approach including gems in a vim extension.

You are using rvm, try to replace the bootstrap.vim with 

if !exists('g:HAMMER_INSTALL_PATH')
      let g:HAMMER_INSTALL_PATH = fnamemodify(expand("<sfile>"), ":p:h")
    end

```
if !exists('g:HAMMER_SILENCE_WARNINGS')
  let g:HAMMER_SILENCE_WARNINGS = 0
endif

if !exists('g:HAMMER_DIRECTORY')
  if has('win32') || has('win64')
    let g:HAMMER_DIRECTORY = $TEMP
  else
    let g:HAMMER_DIRECTORY = '/tmp'
  end
endif

if !exists('g:HAMMER_BROWSER')
  if has('mac')
    let g:HAMMER_BROWSER = 'open'
  elseif has('win32') || has('win64')
    ruby require 'hammer/vim-windows/rubygems'
    let g:HAMMER_BROWSER = 'start'
  elseif has('unix') && executable('xdg-open')
    let g:HAMMER_BROWSER = 'xdg-open'
  else
    let g:HAMMER_BROWSER = ''
  end
endif

if !exists('g:HAMMER_TEMPLATE')
  let g:HAMMER_TEMPLATE = 'default'
endif

ruby $: << File.join(Vim.evaluate('g:HAMMER_INSTALL_PATH'), 'lib')
ruby require 'hammer'
ruby Hammer.load_dependencies!
ruby Hammer.load_renderers!

if has('ruby')
  function! Hammer()
    ruby <<RENDER!
      require 'tilt'
      buffer = Vim::Buffer.current.extend Vim::ImprovedBuffer
      Hammer.render!(buffer)
RENDER!
  endfunction
else
  function! Hammer()
    echo "Sorry, hammer.vim requires vim to be built with Ruby support."
  endfunction
end

:command! Hammer :call Hammer()
```

If you now run `:Hammer` you should detect the load path of your ruby bindings in Vim in the quickfix window. Hope this is not too complex for you to try. **Before** you delete the old ruby bindings, make a backup, so that you can save you system.

Hope this helps you.

**Comment by ghost** [comment]
A lot more straightforward example:

``` shell
$ rvm system
$ gem install <list of gems>
$ vim
```

Also see the README notes for RVM users.

**Comment by henry4j** [comment]
I got rid of RVM out of this equation.
I got into another issue, where I found met_dependencies has 2x the dependencies --- somehow loaded twice.

```
 27     def dependencies_met?
 28       dependencies == dependencies & met_dependencies # this fixed the issue on my box.
 29     end
```

**Comment by wikimatze** [comment]
@henry4j is working now for you with or without the RVM?

**Comment by henry4j** [comment]
without RVM, and w/ my code change above, it works great --- one issue got fixed by my change.
with RVM, I have 2x the dependencies and albino dependency is missing --- two issues.

**Comment by wikimatze** [comment]
Nice :) - but this is bad for RVM user, we have to figure out how to fix it properly for all different ruby installations. I will contact the vim user group and try to ask for different approaches to solve this problem.

Thanks for experimenting @henry4j , it takes a lot of time but in the end, it will help us.

**Comment by olalonde** [comment]
I have the same problem here on OS X Lion (regular vim, no rvm). 

$ gem -v; ruby -v; 
1.3.6
ruby 1.8.7 (2010-01-10 patchlevel 249) [universal-darwin11.0]

**Comment by olalonde** [comment]
_FIXED!_

Apparently vim bundled with OS X is not compiled with Ruby support. Here's a brew package that will install vim with Ruby support:

```
brew install https://raw.github.com/adamv/homebrew-alt/master/duplicates/vim.rb;
ln -s /usr/local/Cellar/vim/7.3.444/bin;
sudo ln -f -s /usr/local/Cellar/vim/7.3.444/bin/vim `which vim`;
```

See http://blog.jerodsanto.net/2011/08/brew-install-vim/

**Comment by wikimatze** [comment]
Hi olalonde,

thanks for your post and problem solution. We will update the README with the solution you want to mention. For the other guys who have problems with rbenv, I created a blog-entry http://wikimatze.de/compiling-vim-from-source-for-ubuntu-and-mac-with-rbenv.html which describes how to build macvim against with ruby support.

**Comment by OJ** [comment]
@olalonde In my case, I tend to use console-based VIM for a number of reasons in a few scenarios, one of which is that a large number of plugins don't work with it :) It's perfectly valid for console VIM to not be built with Ruby while the GUI version is.

The Brew install does remove the problem, but the script still needed to be fixed up.

Thanks for the response mate!
OJ

**Comment by ghost** [comment]
I have removed Albino as a dependency (we weren't using it). Any errors relating to it being unavailable should be gone. I did a fresh install this morning and I experienced none of the problems reported on this issue. The most important installation tip I have is that you are absolutely sure you are installing the gems into a Ruby installation that vim is built against (for me, that is the Ruby shipped with OSX). 

`sudo /usr/bin/gem install <list of dependencies>` is what I had to do but it could be different for you.

**Comment by wikimatze** [comment]
@all, does anybode still have problems with this? Now that albino has gone, no more problems are open. If that is the case, I would like to close this ticket.

**Comment by ghost** [comment]
This isn't an issue for me, although it never was to begin with. I am confident any errors reported in this issue were due to having multiple rubies available, but installing gems into a Ruby installation that isn't the one Vim is built against.

**Comment by olalonde** [comment]
My issue was solved by compiling Vim with Ruby support enabled. (default Vim on OS X doesn't support Ruby)

**Comment by wikimatze** [comment]
I will add this issue to the wiki.
