### ISSUE TITLE
Multi-platform support

### ISSUE THREAD

**Issue by smith** [wikimatze/hammer.vim#4]
Modify the open command so that instead of using `open` it can use `start` on Windows and `lynx` or something when there's no GUI.

**Comment by ghost** [comment]
The solution to this problem involves too much guess work, particularly when Linux and BSD are involved. 

Linux/BSD doesn't have anything similar to "open" on OSX or "start" on Windows(that I know of), and trying to guess what browser a person might have installed is guess work at best. 

It's for those reasons that I'm going to reject this issue, unless you can propose a solution that can handle all operating systems transparently, without delving into RUBY_PLATFORM.

Thanks.

**Comment by smith** [comment]
No problem. Thanks for the consideration, and you are right. I might make a fork with this since I have a more deterministic work environment.

**Comment by ghost** [comment]
Feel free to fork.  
I'm open to solutions that might solve this issue for Linux+BSD, OSX, and Windows.
