### ISSUE TITLE
rst support

### ISSUE THREAD

**Issue by tlatsas** [wikimatze/hammer.vim#45]
Hi, 

README states that `rst` is supported using python `docutils`. I have `docutils` for both python2 and python3 but it doesn't seem to work. Do I need a custom render for that or something?

Thanks.

**Comment by wikimatze** [comment]
Hi,

I looked into https://github.com/matthias-guenther/hammer.vim/tree/master/plugin/hammer.vim/renderers and you are actually right, there isn't a renderer. I'm not quite familiar with python `docutils` are you cabable of adding such a feature on your own? If not I have to put this feature on a nice to have list of this plugin.

Thanks for reporting this issue.

**Comment by tlatsas** [comment]
Hi,

I'll look into it later and make a pull request, should be easy calling `rst2html` (I guess).

**Comment by wikimatze** [comment]
Just what I had in mind, we will see if it is so easy.

**Comment by tlatsas** [comment]
Hello again,

It seems I spoke too soon. Github markup should render `rst` files fine through their `rest2html` [script](https://github.com/github/markup/blob/master/lib/github/commands/rest2html). When I run this script from the command line using:

```
$ python2 rest2hml foo.rst
```

 it renders fine, but from within the ruby environment it fails.

This is due to the Archlinux packaging decisions about python, as `python` points to the python 3 executable and `python2` to the version 2.7.x. This in conjunction with the `rest2html` shebang line pointing to python (version 3 in Archlinux) breaks the rendering.

I think it's time to bring this to github/markup, should be easy to make the script run on both python version. Cheers.

**Comment by tlatsas** [comment]
Hi, it should be fixed when they ship a new version github/markup. See: github/markup#148. Closing.
