### ISSUE TITLE
vim crashes when trying to open a preview

### ISSUE THREAD

**Issue by bitboxer** [wikimatze/hammer.vim#7]
I updated Janus and now everytime I try to open a preview of a markdown file, I get this:

```
Vim: Caught deadly signal SEGV
Vim: Finished.
6;35M 162H6;36M$12;0M
```

Other ruby based plugins (e.g. command-t) are working fine.

**Comment by ghost** [comment]
It's really hard to debug this without an environment I can reproduce it in.
I've got a suspicion that extending Vim::Buffer.current might be the cause, but that'd be a wild guess.

**Comment by bitboxer** [comment]
Yeah, I can understand that :( . If there is anything I can do to pinpoint the problem, I would love to do so. With the old markdown_preview.vim it worked without any problem.

**Comment by ghost** [comment]
Anything you can think of that'd reproduce the problem would be great.
What vim version are you running? Do you have an example of the markdown file you're using?

**Comment by bitboxer** [comment]
Any md-File I tried triggers this. Even simple ones like

```
# Title
hello
```

I am currently using the latest version brew installes (7.3-57).

At the moment I am trying to pinpoint the problem. When I deactivate the line

```
f.write Hammer.render { GitHub::Markup.render(buffer.basename, buffer[1..-1]) }
```

in the hammer.vim, it's not crashing anymore.

**Comment by bitboxer** [comment]
I now think it's the `GitHub::Markup.render`, i will investigate this further tonight when i have more time for this.

**Comment by ghost** [comment]
hm.. yeah, I'd guess the Vim::Buffer#[] method (which I added - for Range support), could also be a culprit.
Thanks for taking the time to debug it, leave any updates you've got here :-)

**Comment by bitboxer** [comment]
Okay, found the problem. I didn't install the redcarpet gem in the system ruby, i only installed it in the rvm ruby i am using on the command line. After installing it in the correct ruby environment, it worked perfectly...

**Comment by ghost** [comment]
Great to hear, thanks :-)
