### ISSUE TITLE
hammer.vim fails at line 6 when Vim started with rvm-controlled environment

### ISSUE THREAD

**Issue by edwardsmit** [wikimatze/hammer.vim#8]
My whole setup of MacVim is done while not running RVM for ruby (essentially using "rvm system") However, I frequently start mvim from the command-line while I _am_ within a rvm-controlled environment. It is on this occasions that hammer.vim is running into problems: 

line    6:
LoadError: /Library/Ruby/Site/1.8/rubygems/custom_require.rb:31:in `gem_original_require': no such file to load -- github/markup

Do you know what's causing this?
Edward

**Comment by ghost** [comment]
I experience the same bug anytime _RVM_ is not set to use the _Ruby_ that _vim_ is built against.
@wayneeseguin, any thoughts on what the cause might be?

**Comment by ghost** [comment]
This problem looks like it is caused by _RVM_ setting RubyGems environment variables, which point the _$LOAD_PATH_ at the paths for whatever Ruby is currently selected by _RVM_, and that's why we get a _LoadError_ from the _Ruby_ that _vim_ is built against. 

I'm not sure how to solve this one. It'll need the input of wayne.

**Comment by edwardsmit** [comment]
Appreciate your efforts. I hope Wayne can help us :)

**Comment by ghost** [comment]
As a workaround. Adding this to your _.zshrc_ or _.bashrc_ fixes the problem for me:

```
 function mvim()
 {
    # spawn a sub-shell, unset environment variables for the sub-shell, start mvim. 
    (unset GEM_PATH; unset GEM_HOME; command mvim "$@")
 }
```

Then, as normal:
`$ mvim`

**Comment by ghost** [comment]
I talked to Wayne on IRC, and there isn't much else we can do to solve this problem.
For people running into this problem, I recommend adding the `mvim()` function to your _$HOME/.bashrc_ or _$HOME/.zshrc_ file.

I'll leave this issue open so it is easily findable by others.

**Comment by wayneeseguin** [comment]
You can do both unsets together, pedantically speaking.

```
mvim()
{
  (unset GEM_PATH GEM_HOME; command mvim "$@")
}
```

**Comment by ghost** [comment]
Excellent, thanks Wayne!

**Comment by edwardsmit** [comment]
Thanks Wayne, added it to my .profile and works like a charm.

**Comment by wayneeseguin** [comment]
btw, thanks for bringing hammer.vim to my attention :)

**Comment by wjbuys** [comment]
The workaround above breaks running gem-provided commands from within vim:

```
:!rake

/home/jacob/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/site_ruby/1.9.1/rubygems.rb:314:in `bin_path': can't find gem rake ([">= 0"]) with  executable rake (Gem::GemNotFoundException)
          from /home/jacob/.rvm/gems/ruby-1.9.2-p290@global/bin/rake:19:in `<main>'
```

Any other ideas?

**Comment by ghost** [comment]
You should ask on the RVM tracker on how to solve that. RVM is messing up your environment, not Hammer.

**Comment by brianarn** [comment]
I found this issue first, and I was hesitant to set the mvim alias above, then I found #12 that had a solution that worked well for me, so I'm copying it over here from @robgleeson.

```
$ rvm system
$ [sudo] gem install github-markup
$ [sudo] gem install redcarpet
```

I think the real key was the `rvm system` bit, which I swear I'd done at one point but just re-running those commands, and now everything is wonderful and life is happy.
