### ISSUE TITLE
doesn't recognize github-markup on windows

### ISSUE THREAD

**Issue by jmcantrell** [wikimatze/hammer.vim#9]
I've installed github-markup, but I still get this on startup:

```
line    6:
LoadError: no such file to load -- github/markup
```

**Comment by ghost** [comment]
I'm going to need a little bit more information about your environment, because it could be one of many things.
- do you only have one Ruby installation?  
  If not, did you install the gem on the Ruby built against vim?
- are you using RVM?  
  (in cgywin or similar)

**Comment by jmcantrell** [comment]
Yes. One ruby install.
How can I tell what version of ruby vim was compiled against? (this is the windows version from vim.org)
No RVM.

**Comment by ghost** [comment]
Can you check if `:ruby p RUBY_DESCRIPTION` matches `ruby -v` just to make sure nothing weird is going on?
You could also check if this script works outside of _vim_, as well as making sure `gem list -l` includes _github-markup:_

```
require 'rubygems'
require 'github/markup' 
```

I don't have a Windows machine to try and reproduce this problem, so anything you could try would be great.

**Comment by jmcantrell** [comment]
Vim's ruby version does match the system's version.
github-markup is in the gem list
The test script works.

**Comment by jmcantrell** [comment]
Also, I'm perfectly happy to help you debug it. I just don't know enough about ruby to offer any suggestions.

**Comment by ghost** [comment]
OK. Thanks. I'll try to get access to a Windows machine over the coming days and create an environment that can reproduce this bug.

**Comment by ghost** [comment]
I got access to a Windows machine for a few hours, and to be honest, I'm not sure why _Vim_ cannot load any _RubyGems_.
I did write up a hack to solve this problem, though, and it worked for me. `RedCarpet` caused _Vim_ to crash, but I could preview _textile_ documents without a hitch, so I'm assuming it was a bad build environment for _RedCarpet_.

Let me know how it works out for you.

**Comment by jmcantrell** [comment]
It does clear up the error. Thanks!

**Comment by artm** [comment]
thanks, the problem did go away for me too
